---
title: "Mining Impactful Discoveries"
author: "Erwan Moreau"
date: "11/4/2021"
output: html_document
---


```{r setup, include=FALSE}
library(knitr)
library(rmarkdown)
library(ggplot2)
source('discoveries3.R')
knitr::opts_chunk$set(echo = TRUE)
# TODO temporary path
dataPath <- './1.prod.log.global.tsv'
dataPathStatic <- paste(dataPath,'across-all-years',sep='/')
```


TODO: This part assumes that the data from the first step has been computed and is available as a file; see first step


# Loading data

## Surges data

```{r loading surges}
all_surges <- fread(surgesDataPath)
```

## Static data

This data table will contain the global frequency statistics across time

```{r loading static}
static_joint <- loadStaticData(dataPathStatic)
```

# Refining target surges

```{r max surges}
surges <- filterSurges(all_surges,oneSurgeByKey='max',minTrend=2)
```

# Adding PMI and conditional probabilities


```{r pmi}
local_final <- addStaticAssociationToRelations(local_surges[surge==TRUE,], static_data, filterMeasures = c('pmi','npmi'))
global_final <- addStaticAssociationToRelations(global_surges[surge==TRUE,], static_data, filterMeasures = c('pmi','npmi'))
```

```{r}
selected_cols <- c('year','term.c1','term.c2','trend','prob.C1GivenC2',	'prob.C2GivenC1',	'pmi'	)
```

```{r table1}
local_final <- local_final[order(-pmi),]
selected <- head(local_final[,..selected_cols],10)
kable(selected)
#kable(selected[order(year),])
```

```{r table2}
global_final <- global_final[order(-pmi),]
selected <- head(global_final[,..selected_cols],10)
#kable(selected[order(year),])
```