---
title: "Detecting Discovery Surges"
author: "Erwan Moreau"
date: "9/16/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rmarkdown)
library(ggplot2)
source('discoveries2.R')
knitr::opts_chunk$set(echo = TRUE)
dataPath <- '../data/21-extract-discoveries'
dirALS <- paste(dataPath,"ALS.min100",sep='/')
N <- 10
```

```{r loading}
indiv <- loadRawData(dir=dirALS, indivOrJoint = 'indiv')
joint <- loadRawData(dir=dirALS, indivOrJoint = 'joint')
totals <- loadTotalFiles(dataPath=dataPath)
```

```{r func}
  repeatShowExample <- function(sourceDF) {
    x <- pickRandom(sourceDF,n=N)
    aggreg_x<-applyAggregMethods(x,totals,idCols=c('source','c1','c2'))
    res_x <- computeSurgeIndicators(aggreg_x)
    dummy_res<-ddply(res_x, c('c1','c2'), function(s) {
      print(paste("************ CASE "))
      print(s[1,c('c1','c2')])
      print(plotRawByYear(s))
      print(plotMAByYear(s))
      print(plotTrendByYear(s[s$aggreg.method=='ma',]))
      print(plotPVNByYear(s))
      print(plotTrendByYear(s[s$aggreg.method=='pvn',]))
      data.frame("dummy result")
    })
  }
```

# KD data

```{r KD}
repeatShowExample(joint[joint$source=='KD',])
```

# PTC data

```{r PTC}
repeatShowExample(joint[joint$source=='PTC',])
```

# MED data

```{r MED}
repeatShowExample(joint[joint$source=='MED',])
```
